export type View =
  | "auth"
  | "home"
  | "explore"
  | "ai"
  | "bookings"
  | "listing"
  | "settings"
  | "admin"
  | "provider"
  | "provider-dashboard"
  | "provider-listings"
  | "provider-reservations"
  | "provider-verification"
  | "contributor"
  | "translate"
